# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form(2).ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BrainQuake_v3(object):
    def setupUi(self, BrainQuake_v3):
        BrainQuake_v3.setObjectName("BrainQuake_v3")
        BrainQuake_v3.resize(797, 534)
        self.pushButton = QtWidgets.QPushButton(BrainQuake_v3)
        self.pushButton.setGeometry(QtCore.QRect(600, 100, 90, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(BrainQuake_v3)
        self.label.setGeometry(QtCore.QRect(80, 60, 80, 32))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BrainQuake_v3)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 80, 32))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(BrainQuake_v3)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 200, 90, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(BrainQuake_v3)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 160, 200, 32))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(BrainQuake_v3)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 200, 200, 32))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(BrainQuake_v3)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 240, 200, 32))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.progressBar = QtWidgets.QProgressBar(BrainQuake_v3)
        self.progressBar.setGeometry(QtCore.QRect(400, 100, 160, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(BrainQuake_v3)
        self.textBrowser.setGeometry(QtCore.QRect(160, 60, 400, 32))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(BrainQuake_v3)
        self.textBrowser_2.setGeometry(QtCore.QRect(160, 291, 255, 160))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_3 = QtWidgets.QPushButton(BrainQuake_v3)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 60, 90, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView = QtWidgets.QGraphicsView(BrainQuake_v3)
        self.graphicsView.setGeometry(QtCore.QRect(435, 290, 255, 160))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_4 = QtWidgets.QPushButton(BrainQuake_v3)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 240, 90, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_21 = QtWidgets.QTextBrowser(BrainQuake_v3)
        self.textBrowser_21.setGeometry(QtCore.QRect(160, 100, 200, 32))
        self.textBrowser_21.setObjectName("textBrowser_21")

        self.retranslateUi(BrainQuake_v3)
        self.pushButton_3.clicked.connect(BrainQuake_v3.Browse)
        self.pushButton.clicked.connect(BrainQuake_v3.Upload)
        self.progressBar.valueChanged['int'].connect(BrainQuake_v3.Progress)
        self.comboBox_2.editTextChanged['QString'].connect(BrainQuake_v3.Name)
        self.comboBox_3.editTextChanged['QString'].connect(BrainQuake_v3.Id)
        self.comboBox_4.editTextChanged['QString'].connect(BrainQuake_v3.Hos)
        self.pushButton_2.clicked.connect(BrainQuake_v3.Check)
        self.pushButton_4.clicked.connect(BrainQuake_v3.PreView)
        QtCore.QMetaObject.connectSlotsByName(BrainQuake_v3)

    def retranslateUi(self, BrainQuake_v3):
        _translate = QtCore.QCoreApplication.translate
        BrainQuake_v3.setWindowTitle(_translate("BrainQuake_v3", "BrainQuake_v3"))
        self.pushButton.setText(_translate("BrainQuake_v3", "上传"))
        self.label.setText(_translate("BrainQuake_v3", "创建新项目："))
        self.label_2.setText(_translate("BrainQuake_v3", "进度查询："))
        self.pushButton_2.setText(_translate("BrainQuake_v3", "查询"))
        self.comboBox_2.setItemText(0, _translate("BrainQuake_v3", "<name>"))
        self.comboBox_3.setItemText(0, _translate("BrainQuake_v3", "<number>"))
        self.comboBox_4.setItemText(0, _translate("BrainQuake_v3", "Yuquan"))
        self.pushButton_3.setText(_translate("BrainQuake_v3", "浏览"))
        self.pushButton_4.setText(_translate("BrainQuake_v3", "预览"))
